# tryfolder.yml
---
- name: Create main folder and subfolders, convert syslog to CSV, and copy to sub1
  hosts: localhost
  gather_facts: no
  
  vars:
    main_folder_path: "./SYSLOG/"
    end_devices_path: "{{ main_folder_path }}/End devices"
    intermediary_devices_path: "{{ main_folder_path }}/Intermediary Devices"
    script_path: "./convert_syslog.py"
    ip_network_dir: "./IPnetwork"  # Path to the directory containing network addresses

  tasks:
    - name: Create main folder
      file:
        path: "{{ main_folder_path }}"
        state: directory

    - name: Create subfolder End devices
      file:
        path: "{{ end_devices_path }}"
        state: directory

    - name: Create subfolder Intermediary Devices
      file:
        path: "{{ intermediary_devices_path }}"
        state: directory
