---
- name: Collect syslog files from remote devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Collect syslog files
      ansible.builtin.fetch:
        src: "/path/to/syslog/syslog"
        dest: "./SYSLOG/End Devices{{ ansible_hostname }}_syslog"
        flat: yes
